### PR TITLE
Keep transparency for PNG

### PR DESCRIPTION
**Pull request by tomaskavalek**
Added $im->setImageFormat(...) to keep PNG transparency.

### CODE REVIEW

**Comment by rickardw** [comment]
Are you losing transparency for all your PNGs? It's working for me. Setting imageformat is great, but why remove opacity?

**Comment by tomaskavalek** [comment]
Yes, losing transparency for all PNGs which has transparent background. Combination of imageformat and opacity keep losing transparency in my case.

**Comment by rickardw** [comment]
Can you share some PNG:s so I can test? Not experiencing same problems...

**Comment by tomaskavalek** [comment]
Sure. If I try it with opacity on this [image](https://www.tomaskavalek.cz/data/test.png), it fills transparent background with dark green color. Maybe it depends on OS (Linux distro) or version of Imagick – I have latest package for CentOS.

I am using your plugin, because in PHP 7.2 is some bug in GD library – see [https://stackoverflow.com/questions/43455282/php-gd-resizing-causes-artifacts](https://stackoverflow.com/questions/43455282/php-gd-resizing-causes-artifacts). So maybe problem is really in different environment. Look at [https://stackoverflow.com/questions/3538851/php-imagick-setimageopacity-destroys-transparency-and-does-nothing](https://stackoverflow.com/questions/3538851/php-imagick-setimageopacity-destroys-transparency-and-does-nothing) – old, but same.

**Pull request merged**
